export enum ButtonType {
    CANCEL = 'CANCEL',
    DECISION_NO = 'DECISION_NO',
    DECISION_YES = 'DECISION_YES',
    REPORT = 'REPORT',
    SIMPLE_BUTTON = 'SIMPLE_BUTTON',
    SPLIT_BUTTON = 'SPLIT_BUTTON',
    STYLE_PRIMARY = 'STYLE_PRIMARY',
    STYLE_SECONDARY = 'STYLE_SECONDARY'
}

export interface ButtonTypes {
    CANCEL: ButtonType.CANCEL;
    DECISION_NO: ButtonType.DECISION_NO;
    DECISION_YES: ButtonType.DECISION_YES;
    REPORT: ButtonType.REPORT;
    SIMPLE_BUTTON: ButtonType.SIMPLE_BUTTON;
    SPLIT_BUTTON: ButtonType.SPLIT_BUTTON;
    STYLE_PRIMARY: ButtonType.STYLE_PRIMARY;
    STYLE_SECONDARY: ButtonType.STYLE_SECONDARY;
}
